spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/monitoring}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:monitoring}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:monitoring123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8081